-- Furniture catalog v2: accurate cubic footage derived from real packed
-- furniture dimensions (see lib/furniture.ts — the app's canonical table).
-- Every row is upserted so existing databases get the corrected values and
-- fresh installs converge to the same numbers.

INSERT INTO public.furniture_catalog (label, cu_ft, category) VALUES
  ('Twin Bed', 35.8, 'Bedroom'),
  ('Full Bed', 46.3, 'Bedroom'),
  ('Queen Bed', 54.3, 'Bedroom'),
  ('King Bed', 68.3, 'Bedroom'),
  ('Cal King Bed', 66.3, 'Bedroom'),
  ('Bunk Bed', 45.9, 'Bedroom'),
  ('Crib', 23.3, 'Bedroom'),
  ('Dresser', 25, 'Bedroom'),
  ('Chest of Drawers', 25.3, 'Bedroom'),
  ('Nightstand', 6.5, 'Bedroom'),
  ('Wardrobe', 42.8, 'Bedroom'),
  ('Armoire', 52, 'Bedroom'),
  ('Vanity', 11.3, 'Bedroom'),
  ('Bed Frame', 12.7, 'Bedroom'),
  ('Mattress (Twin)', 17.6, 'Bedroom'),
  ('Mattress (Full)', 24.4, 'Bedroom'),
  ('Mattress (Queen)', 29.2, 'Bedroom'),
  ('Mattress (King)', 36.9, 'Bedroom'),
  ('Mattress (Cal King)', 35.8, 'Bedroom'),
  ('Hope Chest', 10.7, 'Bedroom'),
  ('Sofa (3-seater)', 64.3, 'Living Room'),
  ('Sofa (2-seater)', 50.8, 'Living Room'),
  ('Sectional Sofa', 137.5, 'Living Room'),
  ('Loveseat', 42.6, 'Living Room'),
  ('Recliner', 33.3, 'Living Room'),
  ('Ottoman', 7.5, 'Living Room'),
  ('Coffee Table', 12, 'Living Room'),
  ('End Table', 7.3, 'Living Room'),
  ('TV Stand', 15, 'Living Room'),
  ('Media Console', 10.8, 'Living Room'),
  ('Entertainment Center', 50, 'Living Room'),
  ('Bookshelf', 21, 'Living Room'),
  ('Armchair', 21.3, 'Living Room'),
  ('Floor Lamp', 7, 'Living Room'),
  ('Floor Rug', 8, 'Living Room'),
  ('Large Rug', 13.6, 'Living Room'),
  ('Dining Table', 37.5, 'Kitchen'),
  ('Dining Chair', 9.2, 'Kitchen'),
  ('Bar Stool', 4.4, 'Kitchen'),
  ('Refrigerator', 43.8, 'Kitchen'),
  ('Freezer Chest', 23.3, 'Kitchen'),
  ('Microwave', 2.5, 'Kitchen'),
  ('Dishwasher', 12.2, 'Kitchen'),
  ('Stove/Oven', 18.5, 'Kitchen'),
  ('Toaster Oven', 1.3, 'Kitchen'),
  ('Kitchen Island', 30, 'Kitchen'),
  ('Wine Rack', 6, 'Kitchen'),
  ('Desk', 31.3, 'Office'),
  ('Standing Desk', 40, 'Office'),
  ('Office Chair', 17.6, 'Office'),
  ('Filing Cabinet', 13, 'Office'),
  ('Bookshelf (Small)', 10, 'Office'),
  ('Monitor', 3, 'Office'),
  ('Printer', 1.7, 'Office'),
  ('Shredder', 1.5, 'Office'),
  ('Whiteboard', 4, 'Office'),
  ('Workbench', 37.5, 'Garage'),
  ('Tool Chest', 16.7, 'Garage'),
  ('Toolbox (Large)', 2.5, 'Garage'),
  ('Bicycle', 23.1, 'Garage'),
  ('Ladder', 5.6, 'Garage'),
  ('Lawn Mower', 13.3, 'Garage'),
  ('Snowblower', 34.7, 'Garage'),
  ('Christmas Tree Box', 13.9, 'Garage'),
  ('Storage Bin (Large)', 3.5, 'Garage'),
  ('Storage Bin (Medium)', 1.5, 'Garage'),
  ('Bathroom Vanity', 14, 'Bathroom'),
  ('Medicine Cabinet', 1.6, 'Bathroom'),
  ('Laundry Basket', 2.7, 'Bathroom'),
  ('Large Box', 3.4, 'Other'),
  ('Medium Box', 2.4, 'Other'),
  ('Small Box', 1, 'Other'),
  ('Suitcase', 3.9, 'Other'),
  ('Mirror (Large)', 4.2, 'Other'),
  ('Plant (Large)', 13.4, 'Other'),
  ('Vacuum Cleaner', 5.2, 'Other'),
  ('Ironing Board', 2.6, 'Other'),
  ('Pet Crate (Large)', 20.4, 'Other'),
  ('Pet Crate (Small)', 5, 'Other'),
  ('Ceiling Fan', 3.7, 'Other'),
  ('Dehumidifier', 2.1, 'Other'),
  ('Bench', 8, 'Other')
ON CONFLICT (label) DO UPDATE SET
  cu_ft = EXCLUDED.cu_ft,
  category = EXCLUDED.category;
